### ISSUE TITLE
Video Stories completely fail to capture

### ISSUE THREAD

**Issue by Orudeon** [saschaheim/instantgram#23]
You might already know this, depending on how Instagram is deploying the code, but 100% of video stories throw the error 'Did you open any Instagram post? Like for example https://www.instagram.com/p/CIGrv1VMBkS/'. Grabbing them is completely nonfunctional. Photo stories seem unaffected.

Affects both Chrome (106.0.5249.119) and Firefox (106.0) on West Coast united states.

**Comment by saschaheim** [comment]
Confirmed

**Comment by snazss** [comment]
Me too, plus I've noticed which for single and public account stories, https://www.storysaver.net/ it's working for videos as well as photos
Videos aren't distributed anymore in the previous way, something has changed in the past 2-3 days, still that website works flawlessly.
You could take some hints from there
For older than 2-3 days highlights stories, Instantgram doesn't work too, but if you inspect page there's the mp4 file right there

**Comment by saschaheim** [comment]
For now it is not possible anymore to download the fallback mp4 videos directly.

Whatsapp has the same mechanisms and they even go one step further and now also protect photos.
In whatsapp everything now has the file extension .enc

Frightening development but a win for the privacy of users.

I don't know where to start it has become really hard to get on a green branch....

**Comment by snazss** [comment]
> For now it is not possible anymore to download the fallback mp4 videos directly.
> 
> Whatsapp has the same mechanisms and they even go one step further and now also protect photos. In whatsapp everything now has the file extension .enc
> 
> Frightening development but a win for the privacy of users.
> 
> I don't know where to start it has become really hard to get on a green branch....

Hey there, don't give up! I'm not an expert or a programmer, I'm very ignorant, but if a website like that is making this work, there must be a way!

Today I've discovered which there's another Instantgram project from Theus, which just 2-3 days ago has solved this exact issue, now I'm using both Instantgram contemporarily, because yours is better on Instagram posts, and the other is better on stories and highlights.

Idk if you know that other homonym of this project, but both make a perfect one, so you could take some hints from that and give yours about posts! I'll post the link here https://theus.github.io/instantgram/

**Comment by saschaheim** [comment]
Update is on the way ^^

Thanks @snazss

**Comment by saschaheim** [comment]
Fixed
