### ISSUE TITLE
Why does this bookmarklet now require 3rd party domain? What is instantgram.1337.pictures ?

### ISSUE THREAD

**Issue by onmyouji** [saschaheim/instantgram#38]
I think you should clearly state this on your Readme. Previously this bookmarklet didn't require any 3rd party domain, but now all downloaded photos come from 3rd party domain: instantgram.1337.pictures

**Comment by saschaheim** [comment]
It is the same as already explained in the light version because of the HTML Content Security Policy (CSP) introduced by Meta, which makes it no longer possible to include links via script that are not validated by instagram.

So now I have to send the url of the picture or video via base64 to the 3 party url and there I can then download the desired picture/video directly via php by clicking on download
